# Generated by Django 4.1.7 on 2023-04-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="Books",
            new_name="books",
        ),
        migrations.RenameField(
            model_name="author",
            old_name="Description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="author",
            old_name="FirstName",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="author",
            old_name="LastName",
            new_name="last_name",
        ),
        migrations.RenameField(
            model_name="author",
            old_name="Picture",
            new_name="picture",
        ),
        migrations.RemoveField(
            model_name="book",
            name="bookCover",
        ),
        migrations.AddField(
            model_name="book",
            name="book_cover",
            field=models.FileField(blank=True, null=True, upload_to="files/bookcovers"),
        ),
        migrations.AddField(
            model_name="book",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="likedislike",
            name="value",
            field=models.IntegerField(),
        ),
    ]
