# Generated by Django 4.1.7 on 2023-03-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_minniebooksuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='minniebooksuser',
            name='profilePicture',
            field=models.FileField(null=True, upload_to='files/pictures'),
        ),
    ]
